const env = {
  NODE_ENV: '',
  PORT: 0,
  API_VERSION: '',
  
  FIREBASE_PROJECT_ID: '',
  FIREBASE_PRIVATE_KEY_ID: '',
  FIREBASE_PRIVATE_KEY: '',
  FIREBASE_CLIENT_EMAIL: '',
  FIREBASE_CLIENT_ID: '',
  
  AWS_ACCESS_KEY_ID: '',
  AWS_SECRET_ACCESS_KEY: '',
  AWS_REGION: '',
  AWS_S3_BUCKET_NAME: '',
  
  JWT_SECRET: '',
  JWT_EXPIRES_IN: '',
  JWT_REFRESH_SECRET: '',
  JWT_REFRESH_EXPIRES_IN: '',
  
  WHATSAPP_API_URL: '',
  WHATSAPP_PHONE_NUMBER_ID: '',
  WHATSAPP_ACCESS_TOKEN: '',
  
  RATE_LIMIT_WINDOW_MS: 0,
  RATE_LIMIT_MAX_REQUESTS: 0,
  
  LOG_LEVEL: '',
  LOG_FORMAT: '',
  
  CORS_ORIGIN: '',
  
  DEFAULT_PAGE_SIZE: 0,
  MAX_PAGE_SIZE: 0,
};

export default env;
